app1_deals/urls.py
from django.urls import path
from . import views

app_name = 'deals'

urlpatterns = [
    path('', views.deals, name='deals'),
    path('add_deal', views.add_deal, name='add_deal'),
    path('/', views.reload_index, name='reload_index')
]

app2_goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.goods, name='goods'),
    path('autocomplete/', views.goods_autocomplete, name='goods_autocomplete'),
    path('public/<str:signed_data>/', views.goods_public, name='goods_public'),

    path('/', views.reload_index, name='reload_index')
]

app3_workers/urls.py
from django.urls import path
from . import views

app_name = 'workers'

urlpatterns = [
    path('', views.workers, name='workers'),

    path('/', views.reload_index, name='reload_index')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('deals/', include('app1_deals.urls', namespace='deals')),
    path('goods/', include('app2_goods.urls', namespace='goods')),
    path('workers/', include('app3_workers.urls', namespace='workers'))
]

main/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth

@main_auth(on_start=True, set_cookie=True)
def index(request):
    ''' Главная страница - перенаправляет на приложения '''

    user_name = f'{request.bitrix_user.first_name} {request.bitrix_user.last_name}'
    return render(request, 'main/index.html', locals())

main/templates/main/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Здравствуйте {{ user_name }}!</h1>
    <hr>
    <ul>
        <li><a href="{% url 'deals:deals' %}">Приложение 1: Управление сделками</a></li>
        <li><a href="{% url 'goods:goods' %}">Приложение 2: Товары и QR-коды</a></li>
        <li><a href="{% url 'workers:workers' %}">Приложение 3: Таблица сотрудников</a></li>
        <li><a href="/app4/">Приложение 4: Вывод компаний на карте</a></li>
        <li><a href="/app5/">Приложение 5: Импорт и экспорт контактов</a></li>
    </ul>
</body>
<!--<script src="//api.bitrix24.com/api/v1/"></script>-->
</html>