app3_workers/urls.py
from django.urls import path
from . import views

app_name = 'workers'

urlpatterns = [
    path('', views.workers, name='workers'),

    path('/', views.reload_index, name='reload_index')
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('deals/', include('app1_deals.urls', namespace='deals')),
    path('goods/', include('app2_goods.urls', namespace='goods')),
    path('workers/', include('app3_workers.urls', namespace='workers'))
]

app3_workers/models.py
from django.db import models

# Create your models here.

app3_workers/views.py
from django.http import HttpResponse


from django.shortcuts import render

from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth

from .services import api_workers_info, get_department_names, chief_froward_list


# Create your views here.
@main_auth(on_cookies=True)
def workers(request):
    but = request.bitrix_user_token

    api_info = api_workers_info(but)

    active_workers_list = api_info['active_workers_list']
    # хеш для работников по id
    users_by_id = {int(user['ID']): user for user in active_workers_list}

    department_list = api_info['department_list']
    # хеш для отделов по id
    departments_by_id = {int(dep['ID']): dep for dep in department_list}

    result = {}
    for user in active_workers_list:
        user_id = int(user['ID'])
        department_names = get_department_names(departments_by_id, user)
        chiefs = chief_froward_list(departments_by_id, users_by_id, user)
        chief_names = [f"{c['NAME']} {c['LAST_NAME']}" for c in chiefs]
        result[user_id] = {'NAME': user.get('NAME'),
                           'LAST_NAME': user.get('LAST_NAME'),
                           'DEPARTMENTS': department_names,
                           'CHIEFS': chief_names}

    return render(request, 'app3_workers/workers.html', locals())


@main_auth(on_cookies=True)
def reload_index(request):
    ''' Главная страница для возвращения по кнопке "На главную". Загружается по куки '''

    user_name = f'{request.bitrix_user.first_name} {request.bitrix_user.last_name}'
    return render(request, 'main/index.html', locals())

app3_workers/templates/app3_workers/workers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <nav>
            <a href="{% url 'workers:reload_index' %}">На главную</a>
        </nav>
        <hr>
    </div>
    <h2>Таблица сотрудников</h2>
    <table border="1" cellspacing="0" cellpadding="5">
        <thead>
            <tr>
                <th>Работник</th>
                <th>Отделы</th>
                <th>Начальники</th>
            </tr>
        </thead>
        <tbody>
            {% for user_id, info in result.items %}
            <tr>
                <td>{{ info.NAME }} {{ info.LAST_NAME }}</td>
                <td>
                    {% if info.DEPARTMENTS %}
                        {% for dep in info.DEPARTMENTS %}
                            {{ dep }}<br>
                        {% endfor %}
                    {% else %}
                        <em>нет данных</em>
                    {% endif %}
                </td>
                <td>
                    {% if info.CHIEFS %}
                        {% for chief in info.CHIEFS %}
                            {{ chief }} <br>
                        {% endfor %}
                    {% else %}
                        <em>—</em>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>